CREATE TABLE branch (
  branchNo INT NOT NULL PRIMARY KEY,
  street VARCHAR(255) NOT NULL,
  city VARCHAR(255) NOT NULL,
  postcode VARCHAR(255) NOT NULL
);

CREATE TABLE staff (
  staffNo INT NOT NULL PRIMARY KEY,
  fName VARCHAR(255) NOT NULL,
  position VARCHAR(255) NOT NULL,
  sex CHAR(1) NOT NULL,
  DOB DATE NOT NULL,
  salary DECIMAL(10,2) NOT NULL
);
